### ISSUE TITLE
vim-racket conflicting with SLIMV

### ISSUE THREAD

**Issue by dkvasnicka** [wlangstroth/vim-racket#15]
I have both Slimv and this plugin loaded and I'm getting the following on various occasions (paredit wrap, completion etc.)

```
Error detected while processing function PareditWrap..<SNR>60_SetKeyword:
line    3:
E474: Invalid argument: iskeyword+=+,-,*,/,%,<,=,>,:,$,?,!,@-@,94,~,#,|,&
Press ENTER or type command to continue
```

The core of the problem is `Invalid argument: iskeyword+=+,-,*,/,%,<,=,>,:,$,?,!,@-@,94,~,#,|,&` -- that's always present in the error message. Can this be fixed or worked around? (I feel like getting rid of Slimv is not an option for me)

**Comment by wlangstroth** [comment]
Not sure - I've never used slimv. I'll see if there's a workaround.

**Comment by dkvasnicka** [comment]
Judging from Slimv's source code and behaviour it is pretty well aware of Racket. It activates itself upon editing a `rkt` file and provides paredit, swank support etc. I use both Slimv and your plugin in their latest versions (meaning git HEAD) and the only specific settings for Slimv in my `.vimrc` are:

```
let g:lisp_rainbow = 0
let g:paredit_electric_return = 0
let g:slimv_indent_maxlines = 0
```

I think in this particular case `paredit.vim` is a problem:

```
daniel@Daniels-MacBook-Pro [09:13:58] [~/.vim/bundle/slimv] 
-> % grep -rn "iskeyword+=+" .
./ftplugin/slimv.vim:1094:        setlocal iskeyword+=+,-,*,/,%,<,=,>,:,$,?,!,@-@,94,~,#,\|,&
./ftplugin/slimv.vim:1096:        setlocal iskeyword+=+,-,*,/,%,<,=,>,:,$,?,!,@-@,94,~,#,\|,&,.,{,},[,]
./plugin/paredit.vim:260:        setlocal iskeyword+=+,-,*,/,%,<,=,>,:,$,?,!,@-@,94,~,#,\|,&
./plugin/paredit.vim:262:        setlocal iskeyword+=+,-,*,/,%,<,=,>,:,$,?,!,@-@,94,~,#,\|,&,.,{,},[,]
```

I'm sorry, I've never written a Vim plugin and so it's difficult for me to come up with something helpful for you :)

**Comment by dkvasnicka** [comment]
I was able to get rid of the error by commenting line 6 from https://github.com/wlangstroth/vim-racket/blob/master/ftplugin/racket.vim out:

```
setl iskeyword+=#,%,^
```

Of course that's just an ugly hack -- but maybe it'll help you to pinpoint the problem. And of course I'm aware of the possibility that the problem actually lies in SLIMV, not here.

**Comment by liweijian** [comment]
It works, thank you @dkvasnicka

**Comment by hendersonreed** [comment]
Commenting because I recently came across the same issue! I was using vim-scripts/paredit.vim, which appears to be unmaintained - the issue noted here was recently fixed however in https://github.com/kovisoft/paredit/issues/37, which seems to be the official mirror.

**Comment by cwfoo** [comment]
@hendersonreed Please don't use anything from the [vim-scripts](https://github.com/vim-scripts) GitHub account if you can avoid it. None of the repositories there have been updated since 2016. See the message on https://vim-scraper.github.io.

Anyway, the root cause of this bug is that paredit appends more things to vim-racket's `setl iskeyword+=#,%,^`. It is an error to append more things to `iskeyword` when its last item is `^`. `^` has special meaning in `iskeyword` (the full description is given in `:h isfname`).

**Comment by hendersonreed** [comment]
Gotcha, thanks for the link!

**Comment by dkvasnicka** [comment]
AFAIK kovisoft’s paredit now includes his fork of paredit, so no need to include anything else.

**Comment by dkvasnicka** [comment]
https://github.com/kovisoft/slimv/blob/master/plugin/paredit.vim
