### ISSUE TITLE
Syntax highlighting breaks on type conversions

### ISSUE THREAD

**Issue by langston-barrett** [wlangstroth/vim-racket#17]
Despite type conversions such as `path->string` being in the `racket.vim` syntax file, they are not highlighted properly in Vim. Is this an inherent limitation of Vim's syntax highlighting, or could it be fixed?

**Comment by wlangstroth** [comment]
This problem extends to a few things, like "*" and "!" in function identifiers as well. It isn't an inherent limitation of Vim's syntax highlighting, as the plain scheme syntax highlighting works fine for identifiers like that.

I think it's fair to say I'm out of my depth, though. The number specifications alone give me crossed eyes. I'll add a note in the readme that someone else should probably take over maintenance of this plug-in.

**Comment by siddharthist** [comment]
I'm looking at the default scheme highlighting and the only difference I notice betweent the two are the lines like 
```
let s:cpo_save = &cpo
set cpo&vim
```
and 
```
let &cpo = s:cpo_save
unlet s:cpo_save
```
I really don't have any idea what these do, but might they have something to do with it? I can't really seem to find any other big differences.

**Comment by wlangstroth** [comment]
Just tested this, and `path->string` is highlighted, so I'm closing.
