### ISSUE TITLE
Thoughts on highlighting for typed/racket

### ISSUE THREAD

**Issue by r1b** [wlangstroth/vim-racket#29]
Currently the plugin missing highlighting for many types and keywords specific to typed/racket. Is it within the scope of this plugin to add these? Is it acceptable to [only highlight these keywords when #lang typed/racket is observed](http://vimdoc.sourceforge.net/htmldoc/filetype.html#new-filetype-scripts)?

**Comment by wlangstroth** [comment]
If you have a patch for that, I'd take it. And yes, I think it would be preferable to only highlight those keywords after `#lang typed/racket`.

**Comment by wlangstroth** [comment]
It's been almost four years, so I'm closing this.
