### ISSUE TITLE
vim-plug support?

### ISSUE THREAD

**Issue by roachsinai** [wlangstroth/vim-racket#42]
Hi, is there a plan for vim-plug support? Or how to let it work with vim-plug?

**Comment by jubnzv** [comment]
What do you mean? For me it works with [following configuration](https://github.com/jubnzv/dotfiles/blob/master/.config/nvim/init.vim#L69):

```
Plug 'https://github.com/wlangstroth/vim-racket'    " Racket mode
```

**Comment by roachsinai** [comment]
I used `Plug 'wlangstroth/vim-racket'`, but nothing changed. I have to copy each directory like `ftplugin, indent` to `~/.vim` to let it work.

**Comment by jubnzv** [comment]
> I used `Plug 'wlangstroth/vim-racket'`, but nothing changed. I have to copy each directory like `ftplugin, indent` to `~/.vim` to let it work.

This issue is not related to vim-racket. Make sure that you install [vim-plug](https://github.com/junegunn/vim-plug/wiki/tutorial#setting-up) correctly.

**Comment by roachsinai** [comment]
It seem's I have to change `au BufRead,BufNewFile *.rkt,*.rktl setf racket` to `au BufRead,BufNewFile *.rkt,*.rktl set filetype=racket` at https://github.com/wlangstroth/vim-racket/blob/c08b63500a70b3b654d2467d25f7c9fa4543d43a/ftdetect/racket.vim#L1

**Comment by jubnzv** [comment]
Oh, sure, there is bug in last commit: https://github.com/wlangstroth/vim-racket/pull/40#issuecomment-479394569. I completely forgot about it, I'm sorry.

I just created PR that will fix it.

**Comment by roachsinai** [comment]
Got it.
