### ISSUE TITLE
Please add the `racket` topic to this repo

### ISSUE THREAD

**Issue by spdegabrielle** [wlangstroth/vim-racket#44]
Hi,
Please add the [`racket`](https://github.com/topics/racket) topic to this repo - I think others will be interested and this will help them find it at https://github.com/topics/racket

https://help.github.com/en/articles/classifying-your-repository-with-topics

Kind regards,

Stephen

**Comment by dkearns** [comment]
[`vim-plugins`](https://github.com/topics/vim-plugins) and [`vim`](https://github.com/topics/vim) should probably be added as well.

**Comment by wlangstroth** [comment]
Okay.
