### ISSUE TITLE
Support Vim 8 package management

### ISSUE THREAD

**Issue by cole-miller** [wlangstroth/vim-racket#54]
Vim 8 added a built-in "[packages](https://vimhelp.org/repeat.txt.html#packages)" feature, which to some extent obsoletes plugin managers like pathogen. Integrating with this feature involves a new plugin layout, which luckily can coexist with the old layout: see the [Rust language plugin](https://github.com/rust-lang/rust.vim) for a good example. It would be useful for this plugin to support the Vim 8 approach in a similar way.

**Comment by benknoble** [comment]
Just browsing around, but it is not the case that any new layout is necessary.

Just clone the repo (or submodule it, or whatever) under `~/.vim/pack/PACKAGE_NAME/{start,opt}/racket` (pick one of `start` or `opt`). If `opt`, you'll need to `packadd` when necessary.

**Comment by cole-miller** [comment]
Thanks, must've misunderstood the documentation.
