### ISSUE TITLE
Inclusion in the distributed Vim runtime

### ISSUE THREAD

**Issue by dkearns** [wlangstroth/vim-racket#71]
Would it be possible to send this to Bram for inclusion in the distributed Vim runtime?

It's a much nicer experience for the casual Racketeer if this support is available out of the box.  It's also a bit strange having a Racket interface (`:help mzscheme`) but no default runtime support.

It doesn't have to be kept in sync with all changes here if that is a maintenance burden.  What we do with vim-ruby, for example, is generally just submit a copy before the next major Vim release unless there's been a significant bug fix or feature enhancement.  That way casual users get a good experience and serious users know to install from the Github repo if they want to use the very latest version.

Thanks,
Doug

**Comment by benknoble** [comment]
I would like to propose that my fork https://github.com/benknoble/vim-racket be the one that is included. It largely builds on the work here, but is more actively maintained (as you may have noticed).

Also, the `mzscheme` is currently only compatible with Racket BC as far as I'm aware. I'm not sure if efforts to create a reasonable interface for Racket CS are underway or not, but CS is considered the primary platform for Racket now.

**Comment by dkearns** [comment]
I'm sure that would be fine, thanks.

Let me know if you want me to help with preparing it.

**Comment by benknoble** [comment]
@dkearns in case you weren't notified, see https://github.com/benknoble/vim-racket/issues/7
