### ISSUE TITLE
vim-racket interacts poorly with syntastic

### ISSUE THREAD

**Issue by ezyang** [wlangstroth/vim-racket#9]
(Don't know if I should file a bug at syntastic instead.) When I have both syntastic and vim-racket in my bundle directory (vanilla install, no extra .vimrc configuration besides pathogen infect), running ':w' on even a small Racket file, e.g.

``` racket
#lang racket
(require redex)
```

results in vim hanging for a few seconds. I don't really know how you'd go about debugging this, but removing either syntastic or vim-racket resolves the problem.

**Comment by xandkar** [comment]
@ezyang Did you ever find a satisfactory solution to this? I just hit upon the same behavior, did some rudimentary debugging and narrowed it down to having `let g:syntastic_enable_racket_racket_checker = 1` in my `.vimrc`.

Whatever Racket file is being edited, writing (`:w`) causes it to be executed - side effects and all :scream: 

Demo:

```
$ cat foo.rkt
#lang racket

(display-to-file "bar" "foo")

$ cat foo
cat: foo: No such file or directory

$ vim -c 'wq' foo.rkt

$ cat foo
bar
```

I noticed the behavior when editing a file with an infinite loop ... :)

**Comment by xandkar** [comment]
I set it to `0` in the meantime, BTW.

**Comment by xandkar** [comment]
Yep, known issue with `syntastic`: https://github.com/vim-syntastic/syntastic/issues/1773
